# Arrays

Arrays are containers of several instances of the same type. For example

In [3]:
a = [1, 4]

2-element Vector{Int64}:
 1
 4

`a` is a two-element vector containing two integers. 
 - Vectors are 1-dimensional arrays,
 - Matrices are 2-dimensional arrays,
 - but there are Arrays of higher dimensions as well!

### Creating Arrays

Many ways of creating arrays:
1. Listing elements

In [4]:
vector = [2, 4, 7]
# or
matrix = [1 3; 4 6]


2×2 Matrix{Int64}:
 1  3
 4  6

Listing elements simply with spaces in between would create a row vector (i.e. a $1\times n$ size matrix)

In [5]:
row_vector = [2 4 7]

1×3 Matrix{Int64}:
 2  4  7

Vectors are aliases for $n\times 1$ matrices, i.e. column vectors.

2. using Julia functions returning an array filled with a particular thing: 

In [6]:
zeros(2,2,3) # returns a 2*2*3 array, filled with 0s

2×2×3 Array{Float64, 3}:
[:, :, 1] =
 0.0  0.0
 0.0  0.0

[:, :, 2] =
 0.0  0.0
 0.0  0.0

[:, :, 3] =
 0.0  0.0
 0.0  0.0

other similar functions:

In [7]:
ones(2,3) # fills with 1s
display(rand(2,3)) # fills with random numbers drawn from a uniform [0,1] distribution
randn(2,3)# fills with random numbers drawn from a standard normal distribution

2×3 Matrix{Float64}:
 0.157874  0.735197   0.31719
 0.751795  0.0967745  0.666044

2×3 Matrix{Float64}:
  0.782263  -0.251015  -0.00793096
 -0.93929    1.74662   -1.5532

There are corresponding functions like these for logical values. When printed, these arrays look like containing 1s and 0s, but that is sort of equivalent to `false`s and `true`s. More on this later.

In [8]:
trues(2,3) # fills with trues (1s)
falses(2,3) # fills with falses (0s)


2×3 BitMatrix:
 0  0  0
 0  0  0

3. you can also give yourself what you want to fill your array with:

In [9]:
fill(42,(3,4)) # or equivalently fill(42,3,4) works too


3×4 Matrix{Int64}:
 42  42  42  42
 42  42  42  42
 42  42  42  42

4. You can also tell Julia to initialize an array containing a certain type, being of certain size without determining its contents. Best way if you really care about performance.

In [10]:
Array{Float64}(undef,3,4)

3×4 Matrix{Float64}:
 9.2243e-312  9.2243e-312  9.2243e-312  9.2243e-312
 9.2243e-312  9.2243e-312  9.2243e-312  9.2243e-312
 9.2243e-312  9.2243e-312  9.2243e-312  9.2243e-312

### Manipulating arrays

How to make different arrays from arrays we already have?

##### Reshape

one important function is reshape: it takes the data from the given array and puts into a new array with dimensions of your choice.

In [11]:
given = [1, 2, 3, 4, 5, 6]

reshape(given,2,3)

2×3 Matrix{Int64}:
 1  3  5
 2  4  6

Note the order in which the new matrix is filled up with data! Julia first filled up column 1, then proceeded to column 2 and finally column 3. This is because Julia is a ***column-major*** language, so matrices are thought of as collections of columns (not rows). A row-major language would have returned
```julia
[1 2 3
 4 5 6]
```
instead. Other column-major languages include Fortran, Matlab and R. On the other hand, C and Python are row-major. This particular ordering of dimensions doesn't only matter for matrices, but for higher dimension arrays as well.

Calling `reshape` when dimensions don't match leads to an error:

In [12]:
reshape(given,2,2)

DimensionMismatch: DimensionMismatch: new dimensions (2, 2) must be consistent with array size 6

#### Exercise

reshape `given` into a column vector!

In [13]:
# work here

reshape(given,6,1)

6×1 Matrix{Int64}:
 1
 2
 3
 4
 5
 6

### Combine several arrays into a bigger one

In [14]:
a = [1, 2]
b = [3, 4]

# to merge into one 4-length column vector
vcat(a,b) # (vertical concatenation) or
[a;b]

4-element Vector{Int64}:
 1
 2
 3
 4

In [15]:
# to merge into a 2x2 matrix
hcat(a,b) # or
[a b]

2×2 Matrix{Int64}:
 1  3
 2  4


`hcat` and `vcat` stand for horizontal and vertical concatenation, respectively. There is also a more general function called `cat`, which can be used to concatenate over any dimension and is therefore useful when working with multidimensional arrays. 

Also good to check what wouldn't work: `[a, b] ` does not simply concatenate the two vectors into a matrix. Instead, it creates a 2-element vector, such that its elements are the given vectors!

In [16]:
[a, b] 

2-element Vector{Vector{Int64}}:
 [1, 2]
 [3, 4]

This would work:

In [17]:
hcat([a, b]...)

2×2 Matrix{Int64}:
 1  3
 2  4

the `...` thing is called the splatting operator. It converts the vector into a list of arguments to be passed to a function. Sometimes useful to know, but don't worry if it looks confusing, one can survive without it.

### Accessing elements of arrays

To main ways of accessing one element of a matrix `A`:
 - `A[i]` gives you the ith element of `A`. Julia performs the counting column-wise
 - `A[i,j]` gives you the element of `A` in the ith row and jth column. This notation should be familiar from linear algebra.

More generally, for an n-dimensional array `A`, we access an elements as `A[something]`, where something is either one positive integer, or a list of n positive integers.

> #### Important
> In Julia indexing is 1-based, i.e. the first element of any iterable object has index 1. This contrasts to languages featuring 0-based indexing, such as C, Python or Java. Less headache.


In [18]:
A = randn(3,6)

3×6 Matrix{Float64}:
 -0.661311  -1.11733   -0.737345  -0.103074   2.0823    1.6612
 -0.261357   1.4569    -0.240429  -1.21094   -0.191775  1.27428
 -1.53382   -0.752337  -0.992121   0.802837   0.303766  1.75927

In [19]:
A[6]

-0.7523366403035061

columns of `A` contain 3 elements each, so the 6th element is the last element of column 2

In [20]:
A[3,2]

-0.7523366403035061

How to use indices for arrays of arrays?

In [21]:
c = [a, b] 

2-element Vector{Vector{Int64}}:
 [1, 2]
 [3, 4]

In [22]:
c[1]

2-element Vector{Int64}:
 1
 2

In [23]:
c[1][2]

2

### Ranges

To access several elements of arrays, we first need to get acquainted with ranges.

In [24]:
2:4

2:4

Consider `2:4`: it behaves very much like a vector `[2, 3, 4]`. For example, we can check that its second element is 3. For this we need parenthesis, otherwise Julia would attempt to access the second element of 4 (and would fail).

In [25]:
(2:4)[2]

3

it is **not** a vector though, but a range. More specifically, a unit range, since the difference between neighboring elements in 1.

In [26]:
println(typeof(2:4))
println(typeof([2,3,4]))

UnitRange{Int64}
Vector{Int64}


we can actually turn this thing into a vector by running `collect`

In [27]:
collect(2:4)

3-element Vector{Int64}:
 2
 3
 4

`2:4` simply means: 'all integers from 2 to 4'. For most practical purposes this works like a vector, but does not need to actually create an object containing all numbers between 2 and 4 and hence less memory is occupied.

### Accessing subsets of arrays 

we take subsets of arrays like

`A[row_indices_we_want,column_indices_we_want]`

For example:

In [28]:
A[1:2,2:3]

2×2 Matrix{Float64}:
 -1.11733  -0.737345
  1.4569   -0.240429

In [29]:
A[1,2:3]

2-element Vector{Float64}:
 -1.1173341581523923
 -0.7373446698368239

If you want all indices from one of the dimensions, you can write `:`

In [30]:
A[1,:] # whole 1st row

6-element Vector{Float64}:
 -0.6613112031275629
 -1.1173341581523923
 -0.7373446698368239
 -0.10307396004153978
  2.0823033069164327
  1.661202592456544

sometimes the `end` keyword is handy

In [31]:
A[:,4:end] # all columns after 4

3×3 Matrix{Float64}:
 -0.103074   2.0823    1.6612
 -1.21094   -0.191775  1.27428
  0.802837   0.303766  1.75927

In [32]:
A[:,4:end-1] # can treat end like a number

3×2 Matrix{Float64}:
 -0.103074   2.0823
 -1.21094   -0.191775
  0.802837   0.303766

### Linear Algebra

With vectors and arrays we can do linear algebra as expected. To use the related package, one need to run

In [33]:
using LinearAlgebra

##### Packages

Why do we need to do that? Most functions and structures in Julia are not loaded automatically, but are found in packages that one needs to load when needed. This way
 - the base language is lighter
 - name conflicts are rare

This is a common behavior (R and Python do the same for example).

Many kinds of packages:
 - some are more 'official' and are even described in the Julia documentation (example: https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/)
 - some are developed by random people/groups and are completely independent (example: https://github.com/SciML/DifferentialEquations.jl).

Some of the official packages are installed automatically along core Julia (LinearAlgebra is like this). All other packages have to be installed on your machine before using the first time.

In [34]:
A = [0 2 0;
     1 0 3]
B = [1 0;
     2 1;
     0 3]
c = [1, 2, 3]
d = [0, 3, 4]; # the ';' character suppresses output


mathematical operations for vectors and matrices work as expected. Dimensions have to match!

In [35]:
c+d

3-element Vector{Int64}:
 1
 5
 7

In [36]:
A*c

2-element Vector{Int64}:
  4
 10

In [37]:
B*c

DimensionMismatch: DimensionMismatch: matrix A has dimensions (3,2), vector B has length 3

In [38]:
c'*B # we had to take the transpose of c

# another way of getting the transpose is tr(c)

1×2 adjoint(::Vector{Int64}) with eltype Int64:
 5  11

In [39]:
M = A*B

2×2 Matrix{Int64}:
 4  2
 1  9

the dot product of two vectors can be obtained by

In [40]:
dot(c,d)

18

another way is simply

In [41]:
c'*d

18

We can solve the

$$ Mx= \begin{bmatrix} 1 \\ 2 \end{bmatrix} $$

equation by running

In [42]:
M\[1,2]

2-element Vector{Float64}:
 0.14705882352941177
 0.20588235294117646

we get the same by inverting `M` manually

In [43]:
inv(M)*[1,2]

2-element Vector{Float64}:
 0.14705882352941177
 0.20588235294117646

For rectangular matrices (i.e. when inverting is impossible), the same command gives the least squares projection.

In [44]:
B\c

2-element Vector{Float64}:
 0.6086956521739129
 0.9782608695652173

### Broadcasting

Sometimes we want to apply such functions to whole arrays element-wise which were meant for individual elements only.

In [45]:
c ^ 3 # throws an error

MethodError: MethodError: no method matching ^(::Vector{Int64}, ::Int64)

Closest candidates are:
  ^(!Matched::Float32, ::Integer)
   @ Base math.jl:1277
  ^(!Matched::Regex, ::Integer)
   @ Base regex.jl:863
  ^(!Matched::Missing, ::Integer)
   @ Base missing.jl:165
  ...


The solution is called *broadcasting*. We simply add a dot after the function or operator!

In [46]:
println(c)
c .^ 3 # this works

[1, 2, 3]


3-element Vector{Int64}:
  1
  8
 27

> #### Important
>
> Usually, white spaces don't matter in Julia, but `.` belongs to the operator on which it is applied, and thus cannot be separated.

For more general functions this works as follows: If `f(arg_1,arg_2,...)` is defined, then `f.` can be applied as `f.(args_1,args_2,...)`, where each `args_i` is a vector consisting of elements like `arg_i` of the original function. 

#### Exercise
 1. write a function that takes two arguments and returns the square of their sum
 2. using this function, compute the square of the sum of 5 with each element of `c`

If you are done, you can also try doing the same task in one line without defining a new function


In [47]:
# work here

function squaresum(x,y)
    return (x+y)^2
end

squaresum.(5,c)

3-element Vector{Int64}:
 36
 49
 64

one line solution, without defining any function:

In [48]:
(5 .+ c).^2

3-element Vector{Int64}:
 36
 49
 64

What happens if we input two arrays to the `squaresum` function? Two cases:
1. if the arguments have the same shape, Julia iterates through them parallelly. First index of `d` with first index of `c`, second with second, etc.

In [49]:
println((d,c))

squaresum.(d,c)

([0, 3, 4], [1, 2, 3])


3-element Vector{Int64}:
  1
 25
 49

2. if not, Julia takes the Cartesian product of the indices, i.e. looks at all the combinations of indices of the two objects. This happens if we make one of the inputs a row vector. For example, the result in the 2nd row and 3rd column is `36`, because the third element of `d` is `4` and second element of `c` is `2` and we get `(4+2)^2`.

In [50]:
squaresum.(reshape(d,1,3),c) # or squaresum.(d',c)

3×3 Matrix{Int64}:
 1  16  25
 4  25  36
 9  36  49

### Useful functions of arrays

In [51]:
A = rand(3,4)

3×4 Matrix{Float64}:
 0.670996  0.697865  0.835244   0.169438
 0.502806  0.249939  0.0511489  0.317309
 0.510362  0.111627  0.795966   0.225291

number of elements:

In [52]:
length(A)

12

a range over all elements:

In [53]:
eachindex(A)

Base.OneTo(12)

dimensions:

In [54]:
size(A)

(3, 4)

length over dimension 2:

In [55]:
size(A,2)

4

range separately over dimensions:

In [56]:
axes(A)

(Base.OneTo(3), Base.OneTo(4))

range separately over dimension 2:

In [57]:
axes(A,2)

Base.OneTo(4)

##### How to add elements to an existing vector?

In [58]:
a = rand(5)

5-element Vector{Float64}:
 0.32775482769191444
 0.47750100529178063
 0.4355109281256926
 0.863795274883595
 0.662902899339634

`push!` adds a new element to the end of the vector. Note that no new vector is created, but `a` is modified! Actually, it is a Julia convention that all functions amending some of its inputs have a `!` in the end of the function name.

In [59]:
push!(a,13.0)

6-element Vector{Float64}:
  0.32775482769191444
  0.47750100529178063
  0.4355109281256926
  0.863795274883595
  0.662902899339634
 13.0

In [60]:
a

6-element Vector{Float64}:
  0.32775482769191444
  0.47750100529178063
  0.4355109281256926
  0.863795274883595
  0.662902899339634
 13.0

`pushfirst!` inserts an element to the first position:

In [61]:
pushfirst!(a, 0.0)

7-element Vector{Float64}:
  0.0
  0.32775482769191444
  0.47750100529178063
  0.4355109281256926
  0.863795274883595
  0.662902899339634
 13.0

`insert!` can insert an element to the position of your choice

In [62]:
insert!(a,3,2.0) # inserts 2.0 to the 3rd position 

8-element Vector{Float64}:
  0.0
  0.32775482769191444
  2.0
  0.47750100529178063
  0.4355109281256926
  0.863795274883595
  0.662902899339634
 13.0